package admin.table.dto;

/**Auto Generated By Hap Code Generator**/
import com.hand.hap.mybatis.annotation.Condition;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
@ExtensionAttribute(disable=true)
@Table(name = "dinner_table")
public class DinnerTable extends BaseDTO {
    @Id
    @Column
    @GeneratedValue(generator = "IDENTITY")
    private Long id;

    @NotEmpty
    @Condition(
         operator = "LIKE"
    )
    @Column
    private String tableName;
    @Column
    private String tableDescription;
    @Column
    @NotEmpty
    private String tableStatus;
    @Column
    @NotEmpty
    private String used;

    public Long getId() {
        return id;
    }

    public DinnerTable setId(Long id) {
        this.id = id;
        return this;
    }

    public String getTableName() {
        return tableName;
    }

    public DinnerTable setTableName(String tableName) {
        this.tableName = tableName;
        return this;
    }

    public String getTableDescription() {
        return tableDescription;
    }

    public DinnerTable setTableDescription(String tableDescription) {
        this.tableDescription = tableDescription;
        return this;
    }

    public String getTableStatus() {
        return tableStatus;
    }

    public DinnerTable setTableStatus(String tableStatus) {
        this.tableStatus = tableStatus;
        return this;
    }

    public String getUsed() {
        return used;
    }

    public DinnerTable setUsed(String used) {
        this.used = used;
        return this;
    }
}
