package admin.food.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "dinner_table")
public class DinnerTable extends BaseDTO {
     @Id
     @GeneratedValue
      private Long id;

     @NotEmpty
      private String tableName;

      private String tableDescription;

     @NotEmpty
      private String tableStatus;

     @NotEmpty
      private String used;


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setTableName(String tableName){
         this.tableName = tableName;
     }

     public String getTableName(){
         return tableName;
     }

     public void setTableDescription(String tableDescription){
         this.tableDescription = tableDescription;
     }

     public String getTableDescription(){
         return tableDescription;
     }

     public void setTableStatus(String tableStatus){
         this.tableStatus = tableStatus;
     }

     public String getTableStatus(){
         return tableStatus;
     }

     public void setUsed(String used){
         this.used = used;
     }

     public String getUsed(){
         return used;
     }

     }
